package platformclientv2
import (
	"github.com/leekchan/timeutil"
	"encoding/json"
	"strconv"
	"strings"
)

// Localencryptionkeyrequest
type Localencryptionkeyrequest struct { 
	// ConfigId - The local configuration id that contains metadata on private local service
	ConfigId *string `json:"configId,omitempty"`


	// PublicKey - Base 64 encoded public key, generated by the local service.
	PublicKey *string `json:"publicKey,omitempty"`


	// KeypairId - The key pair id from the local service.
	KeypairId *string `json:"keypairId,omitempty"`

}

func (o *Localencryptionkeyrequest) MarshalJSON() ([]byte, error) {
	// Redundant initialization to avoid unused import errors for models with no Time values
	_  = timeutil.Timedelta{}
	type Alias Localencryptionkeyrequest
	
	return json.Marshal(&struct { 
		ConfigId *string `json:"configId,omitempty"`
		
		PublicKey *string `json:"publicKey,omitempty"`
		
		KeypairId *string `json:"keypairId,omitempty"`
		*Alias
	}{ 
		ConfigId: o.ConfigId,
		
		PublicKey: o.PublicKey,
		
		KeypairId: o.KeypairId,
		Alias:    (*Alias)(o),
	})
}

func (o *Localencryptionkeyrequest) UnmarshalJSON(b []byte) error {
	var LocalencryptionkeyrequestMap map[string]interface{}
	err := json.Unmarshal(b, &LocalencryptionkeyrequestMap)
	if err != nil {
		return err
	}
	
	if ConfigId, ok := LocalencryptionkeyrequestMap["configId"].(string); ok {
		o.ConfigId = &ConfigId
	}
    
	if PublicKey, ok := LocalencryptionkeyrequestMap["publicKey"].(string); ok {
		o.PublicKey = &PublicKey
	}
    
	if KeypairId, ok := LocalencryptionkeyrequestMap["keypairId"].(string); ok {
		o.KeypairId = &KeypairId
	}
    

	return nil
}

// String returns a JSON representation of the model
func (o *Localencryptionkeyrequest) String() string {
	j, _ := json.Marshal(o)
	str, _ := strconv.Unquote(strings.Replace(strconv.Quote(string(j)), `\\u`, `\u`, -1))

	return str
}
