package platformclientv2
import (
	"encoding/json"
	"strconv"
	"strings"
)

// Localencryptionkeyrequest
type Localencryptionkeyrequest struct { 
	// ConfigId - The local configuration id that contains metadata on private local service
	ConfigId *string `json:"configId,omitempty"`


	// PublicKey - Base 64 encoded public key, generated by the local service.
	PublicKey *string `json:"publicKey,omitempty"`


	// KeypairId - The key pair id from the local service.
	KeypairId *string `json:"keypairId,omitempty"`

}

// String returns a JSON representation of the model
func (o *Localencryptionkeyrequest) String() string {
	j, _ := json.Marshal(o)
	str, _ := strconv.Unquote(strings.Replace(strconv.Quote(string(j)), `\\u`, `\u`, -1))

	return str
}
