package platformclientv2
import (
	"github.com/leekchan/timeutil"
	"reflect"
	"encoding/json"
	"strconv"
	"strings"
)

// Pushdeviceinsertrequest
type Pushdeviceinsertrequest struct { 
	// SetFieldNames defines the list of fields to use for controlled JSON serialization
	SetFieldNames map[string]bool `json:"-"`
	// DeviceToken - The device token generated by the network providers
	DeviceToken *string `json:"deviceToken,omitempty"`

	// NotificationProvider - The notification provider for the device (FCM / APNS)
	NotificationProvider *string `json:"notificationProvider,omitempty"`

	// Language - The preferred language of the user (eg. en-us, de, fr)
	Language *string `json:"language,omitempty"`

	// DeviceType - The type of the device (Android / IoS)
	DeviceType *string `json:"deviceType,omitempty"`
}

// SetField uses reflection to set a field on the model if the model has a property SetFieldNames, and triggers custom JSON serialization logic to only serialize properties that have been set using this function.
func (o *Pushdeviceinsertrequest) SetField(field string, fieldValue interface{}) {
	// Get Value object for field
	target := reflect.ValueOf(o)
	targetField := reflect.Indirect(target).FieldByName(field)

	// Set value
	if fieldValue != nil {
		targetField.Set(reflect.ValueOf(fieldValue))
	} else {
		// Must create a new Value (creates **type) then get its element (*type), which will be nil pointer of the appropriate type
		x := reflect.Indirect(reflect.New(targetField.Type()))
		targetField.Set(x)
	}

	// Add field to set field names list
	if o.SetFieldNames == nil {
		o.SetFieldNames = make(map[string]bool)
	}
	o.SetFieldNames[field] = true
}

func (o Pushdeviceinsertrequest) MarshalJSON() ([]byte, error) {
	// Special processing to dynamically construct object using only field names that have been set using SetField. This generates payloads suitable for use with PATCH API endpoints.
	if len(o.SetFieldNames) > 0 {
		// Get reflection Value
		val := reflect.ValueOf(o)

		// Known field names that require type overrides
		dateTimeFields := []string{  }
		localDateTimeFields := []string{  }
		dateFields := []string{  }

		// Construct object
		newObj := make(map[string]interface{})
		for fieldName := range o.SetFieldNames {
			// Get initial field value
			fieldValue := val.FieldByName(fieldName).Interface()

			// Apply value formatting overrides
			if fieldValue == nil || reflect.ValueOf(fieldValue).IsNil()  {
				// Do nothing. Just catching this case to avoid trying to custom serialize a nil value
			} else if contains(dateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%fZ")
			} else if contains(localDateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%f")
			} else if contains(dateFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%d")
			}

			// Assign value to field using JSON tag name
			newObj[getFieldName(reflect.TypeOf(&o), fieldName)] = fieldValue
		}

		// Marshal and return dynamically constructed interface
		return json.Marshal(newObj)
	}

	// Redundant initialization to avoid unused import errors for models with no Time values
	_  = timeutil.Timedelta{}
	type Alias Pushdeviceinsertrequest
	
	return json.Marshal(&struct { 
		DeviceToken *string `json:"deviceToken,omitempty"`
		
		NotificationProvider *string `json:"notificationProvider,omitempty"`
		
		Language *string `json:"language,omitempty"`
		
		DeviceType *string `json:"deviceType,omitempty"`
		Alias
	}{ 
		DeviceToken: o.DeviceToken,
		
		NotificationProvider: o.NotificationProvider,
		
		Language: o.Language,
		
		DeviceType: o.DeviceType,
		Alias:    (Alias)(o),
	})
}

func (o *Pushdeviceinsertrequest) UnmarshalJSON(b []byte) error {
	var PushdeviceinsertrequestMap map[string]interface{}
	err := json.Unmarshal(b, &PushdeviceinsertrequestMap)
	if err != nil {
		return err
	}
	
	if DeviceToken, ok := PushdeviceinsertrequestMap["deviceToken"].(string); ok {
		o.DeviceToken = &DeviceToken
	}
    
	if NotificationProvider, ok := PushdeviceinsertrequestMap["notificationProvider"].(string); ok {
		o.NotificationProvider = &NotificationProvider
	}
    
	if Language, ok := PushdeviceinsertrequestMap["language"].(string); ok {
		o.Language = &Language
	}
    
	if DeviceType, ok := PushdeviceinsertrequestMap["deviceType"].(string); ok {
		o.DeviceType = &DeviceType
	}
    

	return nil
}

// String returns a JSON representation of the model
func (o *Pushdeviceinsertrequest) String() string {
	j, _ := json.Marshal(o)
	str, _ := strconv.Unquote(strings.Replace(strconv.Quote(string(j)), `\\u`, `\u`, -1))

	return str
}
