package platformclientv2
import (
	"time"
	"github.com/leekchan/timeutil"
	"reflect"
	"encoding/json"
	"strconv"
	"strings"
)

// Speechtextanalyticsconversationsummary
type Speechtextanalyticsconversationsummary struct { 
	// SetFieldNames defines the list of fields to use for controlled JSON serialization
	SetFieldNames map[string]bool `json:"-"`
	// SummaryType - The type of summary
	SummaryType *string `json:"summaryType,omitempty"`

	// MediaType - The media type of the associated interaction
	MediaType *string `json:"mediaType,omitempty"`

	// Language - Language of the summary
	Language *string `json:"language,omitempty"`

	// SourceId - The id of the source (program, agent assistant, or flow) from which summarization is triggered
	SourceId *string `json:"sourceId,omitempty"`

	// Summary - A summarization of the conversation transcription
	Summary *string `json:"summary,omitempty"`

	// Generated - Indicates whether or not the summary was generated by AI
	Generated *bool `json:"generated,omitempty"`

	// DateCreated - Timestamp of when the summary was created. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z
	DateCreated *time.Time `json:"dateCreated,omitempty"`
}

// SetField uses reflection to set a field on the model if the model has a property SetFieldNames, and triggers custom JSON serialization logic to only serialize properties that have been set using this function.
func (o *Speechtextanalyticsconversationsummary) SetField(field string, fieldValue interface{}) {
	// Get Value object for field
	target := reflect.ValueOf(o)
	targetField := reflect.Indirect(target).FieldByName(field)

	// Set value
	if fieldValue != nil {
		targetField.Set(reflect.ValueOf(fieldValue))
	} else {
		// Must create a new Value (creates **type) then get its element (*type), which will be nil pointer of the appropriate type
		x := reflect.Indirect(reflect.New(targetField.Type()))
		targetField.Set(x)
	}

	// Add field to set field names list
	if o.SetFieldNames == nil {
		o.SetFieldNames = make(map[string]bool)
	}
	o.SetFieldNames[field] = true
}

func (o Speechtextanalyticsconversationsummary) MarshalJSON() ([]byte, error) {
	// Special processing to dynamically construct object using only field names that have been set using SetField. This generates payloads suitable for use with PATCH API endpoints.
	if len(o.SetFieldNames) > 0 {
		// Get reflection Value
		val := reflect.ValueOf(o)

		// Known field names that require type overrides
		dateTimeFields := []string{ "DateCreated", }
		localDateTimeFields := []string{  }
		dateFields := []string{  }

		// Construct object
		newObj := make(map[string]interface{})
		for fieldName := range o.SetFieldNames {
			// Get initial field value
			fieldValue := val.FieldByName(fieldName).Interface()

			// Apply value formatting overrides
			if fieldValue == nil || reflect.ValueOf(fieldValue).IsNil()  {
				// Do nothing. Just catching this case to avoid trying to custom serialize a nil value
			} else if contains(dateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%fZ")
			} else if contains(localDateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%f")
			} else if contains(dateFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%d")
			}

			// Assign value to field using JSON tag name
			newObj[getFieldName(reflect.TypeOf(&o), fieldName)] = fieldValue
		}

		// Marshal and return dynamically constructed interface
		return json.Marshal(newObj)
	}

	// Redundant initialization to avoid unused import errors for models with no Time values
	_  = timeutil.Timedelta{}
	type Alias Speechtextanalyticsconversationsummary
	
	DateCreated := new(string)
	if o.DateCreated != nil {
		
		*DateCreated = timeutil.Strftime(o.DateCreated, "%Y-%m-%dT%H:%M:%S.%fZ")
	} else {
		DateCreated = nil
	}
	
	return json.Marshal(&struct { 
		SummaryType *string `json:"summaryType,omitempty"`
		
		MediaType *string `json:"mediaType,omitempty"`
		
		Language *string `json:"language,omitempty"`
		
		SourceId *string `json:"sourceId,omitempty"`
		
		Summary *string `json:"summary,omitempty"`
		
		Generated *bool `json:"generated,omitempty"`
		
		DateCreated *string `json:"dateCreated,omitempty"`
		Alias
	}{ 
		SummaryType: o.SummaryType,
		
		MediaType: o.MediaType,
		
		Language: o.Language,
		
		SourceId: o.SourceId,
		
		Summary: o.Summary,
		
		Generated: o.Generated,
		
		DateCreated: DateCreated,
		Alias:    (Alias)(o),
	})
}

func (o *Speechtextanalyticsconversationsummary) UnmarshalJSON(b []byte) error {
	var SpeechtextanalyticsconversationsummaryMap map[string]interface{}
	err := json.Unmarshal(b, &SpeechtextanalyticsconversationsummaryMap)
	if err != nil {
		return err
	}
	
	if SummaryType, ok := SpeechtextanalyticsconversationsummaryMap["summaryType"].(string); ok {
		o.SummaryType = &SummaryType
	}
    
	if MediaType, ok := SpeechtextanalyticsconversationsummaryMap["mediaType"].(string); ok {
		o.MediaType = &MediaType
	}
    
	if Language, ok := SpeechtextanalyticsconversationsummaryMap["language"].(string); ok {
		o.Language = &Language
	}
    
	if SourceId, ok := SpeechtextanalyticsconversationsummaryMap["sourceId"].(string); ok {
		o.SourceId = &SourceId
	}
    
	if Summary, ok := SpeechtextanalyticsconversationsummaryMap["summary"].(string); ok {
		o.Summary = &Summary
	}
    
	if Generated, ok := SpeechtextanalyticsconversationsummaryMap["generated"].(bool); ok {
		o.Generated = &Generated
	}
    
	if dateCreatedString, ok := SpeechtextanalyticsconversationsummaryMap["dateCreated"].(string); ok {
		DateCreated, _ := time.Parse("2006-01-02T15:04:05.999999Z", dateCreatedString)
		o.DateCreated = &DateCreated
	}
	

	return nil
}

// String returns a JSON representation of the model
func (o *Speechtextanalyticsconversationsummary) String() string {
	j, _ := json.Marshal(o)
	str, _ := strconv.Unquote(strings.Replace(strconv.Quote(string(j)), `\\u`, `\u`, -1))

	return str
}
