package platformclientv2
import (
	"github.com/leekchan/timeutil"
	"reflect"
	"encoding/json"
	"strconv"
	"strings"
)

// Webmessagingmessage - A web messaging message
type Webmessagingmessage struct { 
	// SetFieldNames defines the list of fields to use for controlled JSON serialization
	SetFieldNames map[string]bool `json:"-"`
	// Id - Unique ID of the message. This ID is generated by Messaging Platform. Message receipts will have the same ID as the message they reference.
	Id *string `json:"id,omitempty"`

	// Channel - Channel-specific information that describes the message and the message channel/provider.
	Channel *Webmessagingchannel `json:"channel,omitempty"`

	// VarType - Message type.
	VarType *string `json:"type,omitempty"`

	// Text - Message text.
	Text *string `json:"text,omitempty"`

	// Content - List of content elements.
	Content *[]Webmessagingcontent `json:"content,omitempty"`

	// Status - Message receipt status, only used with type Receipt.
	Status *string `json:"status,omitempty"`

	// Reasons - List of reasons for a message receipt that indicates the message has failed. Only used with Failed status.
	Reasons *[]Reason `json:"reasons,omitempty"`

	// Events - List of event elements.
	Events *[]Webmessagingevent `json:"events,omitempty"`

	// Direction - The direction of the message.  Direction is always from the perspective of the Genesys Cloud platform.  An Inbound message is one sent from a guest to the Genesys Cloud Platform.  An Outbound message is one sent from the Genesys Cloud Platform to a guest.
	Direction *string `json:"direction,omitempty"`

	// OriginatingEntity - Specifies if this message was sent by a human agent or bot. The platform may use this to apply appropriate provider policies.
	OriginatingEntity *string `json:"originatingEntity,omitempty"`

	// Metadata - Additional metadata about this message.
	Metadata *map[string]string `json:"metadata,omitempty"`
}

// SetField uses reflection to set a field on the model if the model has a property SetFieldNames, and triggers custom JSON serialization logic to only serialize properties that have been set using this function.
func (o *Webmessagingmessage) SetField(field string, fieldValue interface{}) {
	// Get Value object for field
	target := reflect.ValueOf(o)
	targetField := reflect.Indirect(target).FieldByName(field)

	// Set value
	if fieldValue != nil {
		targetField.Set(reflect.ValueOf(fieldValue))
	} else {
		// Must create a new Value (creates **type) then get its element (*type), which will be nil pointer of the appropriate type
		x := reflect.Indirect(reflect.New(targetField.Type()))
		targetField.Set(x)
	}

	// Add field to set field names list
	if o.SetFieldNames == nil {
		o.SetFieldNames = make(map[string]bool)
	}
	o.SetFieldNames[field] = true
}

func (o Webmessagingmessage) MarshalJSON() ([]byte, error) {
	// Special processing to dynamically construct object using only field names that have been set using SetField. This generates payloads suitable for use with PATCH API endpoints.
	if len(o.SetFieldNames) > 0 {
		// Get reflection Value
		val := reflect.ValueOf(o)

		// Known field names that require type overrides
		dateTimeFields := []string{  }
		localDateTimeFields := []string{  }
		dateFields := []string{  }

		// Construct object
		newObj := make(map[string]interface{})
		for fieldName := range o.SetFieldNames {
			// Get initial field value
			fieldValue := val.FieldByName(fieldName).Interface()

			// Apply value formatting overrides
			if fieldValue == nil || reflect.ValueOf(fieldValue).IsNil()  {
				// Do nothing. Just catching this case to avoid trying to custom serialize a nil value
			} else if contains(dateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%fZ")
			} else if contains(localDateTimeFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%dT%H:%M:%S.%f")
			} else if contains(dateFields, fieldName) {
				fieldValue = timeutil.Strftime(toTime(fieldValue), "%Y-%m-%d")
			}

			// Assign value to field using JSON tag name
			newObj[getFieldName(reflect.TypeOf(&o), fieldName)] = fieldValue
		}

		// Marshal and return dynamically constructed interface
		return json.Marshal(newObj)
	}

	// Redundant initialization to avoid unused import errors for models with no Time values
	_  = timeutil.Timedelta{}
	type Alias Webmessagingmessage
	
	return json.Marshal(&struct { 
		Id *string `json:"id,omitempty"`
		
		Channel *Webmessagingchannel `json:"channel,omitempty"`
		
		VarType *string `json:"type,omitempty"`
		
		Text *string `json:"text,omitempty"`
		
		Content *[]Webmessagingcontent `json:"content,omitempty"`
		
		Status *string `json:"status,omitempty"`
		
		Reasons *[]Reason `json:"reasons,omitempty"`
		
		Events *[]Webmessagingevent `json:"events,omitempty"`
		
		Direction *string `json:"direction,omitempty"`
		
		OriginatingEntity *string `json:"originatingEntity,omitempty"`
		
		Metadata *map[string]string `json:"metadata,omitempty"`
		Alias
	}{ 
		Id: o.Id,
		
		Channel: o.Channel,
		
		VarType: o.VarType,
		
		Text: o.Text,
		
		Content: o.Content,
		
		Status: o.Status,
		
		Reasons: o.Reasons,
		
		Events: o.Events,
		
		Direction: o.Direction,
		
		OriginatingEntity: o.OriginatingEntity,
		
		Metadata: o.Metadata,
		Alias:    (Alias)(o),
	})
}

func (o *Webmessagingmessage) UnmarshalJSON(b []byte) error {
	var WebmessagingmessageMap map[string]interface{}
	err := json.Unmarshal(b, &WebmessagingmessageMap)
	if err != nil {
		return err
	}
	
	if Id, ok := WebmessagingmessageMap["id"].(string); ok {
		o.Id = &Id
	}
    
	if Channel, ok := WebmessagingmessageMap["channel"].(map[string]interface{}); ok {
		ChannelString, _ := json.Marshal(Channel)
		json.Unmarshal(ChannelString, &o.Channel)
	}
	
	if VarType, ok := WebmessagingmessageMap["type"].(string); ok {
		o.VarType = &VarType
	}
    
	if Text, ok := WebmessagingmessageMap["text"].(string); ok {
		o.Text = &Text
	}
    
	if Content, ok := WebmessagingmessageMap["content"].([]interface{}); ok {
		ContentString, _ := json.Marshal(Content)
		json.Unmarshal(ContentString, &o.Content)
	}
	
	if Status, ok := WebmessagingmessageMap["status"].(string); ok {
		o.Status = &Status
	}
    
	if Reasons, ok := WebmessagingmessageMap["reasons"].([]interface{}); ok {
		ReasonsString, _ := json.Marshal(Reasons)
		json.Unmarshal(ReasonsString, &o.Reasons)
	}
	
	if Events, ok := WebmessagingmessageMap["events"].([]interface{}); ok {
		EventsString, _ := json.Marshal(Events)
		json.Unmarshal(EventsString, &o.Events)
	}
	
	if Direction, ok := WebmessagingmessageMap["direction"].(string); ok {
		o.Direction = &Direction
	}
    
	if OriginatingEntity, ok := WebmessagingmessageMap["originatingEntity"].(string); ok {
		o.OriginatingEntity = &OriginatingEntity
	}
    
	if Metadata, ok := WebmessagingmessageMap["metadata"].(map[string]interface{}); ok {
		MetadataString, _ := json.Marshal(Metadata)
		json.Unmarshal(MetadataString, &o.Metadata)
	}
	

	return nil
}

// String returns a JSON representation of the model
func (o *Webmessagingmessage) String() string {
	j, _ := json.Marshal(o)
	str, _ := strconv.Unquote(strings.Replace(strconv.Quote(string(j)), `\\u`, `\u`, -1))

	return str
}
